### PR TITLE
removes based

### PR DESCRIPTION
**Pull request by swissloaf**
I dont like being asked "BASED on what" every time i attempt to call someone/something based.......

if its based its based!!!!!! not based on anything, its just based!!!

### CODE REVIEW

**Comment by SonixApache** [comment]
based on what

**Comment by Featherfield** [comment]
based on what?

**Comment by Bibby0110** [comment]
based on what?

**Comment by ghost** [comment]
what is the basis behind this PR

**Comment by Irradiation** [comment]
Basé sur quoi?

**Comment by yclatious** [comment]
Baseado em que?

**Comment by swissloaf** [comment]
based

**Comment by boy2mantwicethefam** [comment]
Bazat pe ce?

**Comment by Kharkov72** [comment]
not based.

**Comment by DrSnips** [comment]
Based on THIS *unzips

**Comment by SweptWasTaken** [comment]
image
19 downvotes. Your pr does not seem to be that popular.

**Comment by PJB3005** [comment]
gebaseerd op wat?

**Comment by swissloaf** [comment]
Double-based

**Comment by swissloaf** [comment]
image

**Comment by PJB3005** [comment]
Basde on this PR getting closed

**Pull request closed without merging**
